### ISSUE TITLE
Extend controller getting constructor _class cannot be invoked without 'new' error

### ISSUE THREAD

**Issue by fathiabdulrahim** [stimulus-components/stimulus-checkbox-select-all#8] opened 2020-12-11 17:47 UTC
I was trying to extend the controller for `stimulus-checkbox-select-all` 

```
import CheckboxSelectAll from "stimulus-checkbox-select-all"

export default class extends CheckboxSelectAll {
  connect(){
    super.connect()
    console.log("child controller loaded!")
  }
}
```

but i keep getting this error `Uncaught (in promise) TypeError: Class constructor _class cannot be invoked without 'new'`
any idea why ?

**Comment by darylhai** [comment] 2021-04-09 05:25
I'm also getting this error. Did you figure it out?

**Comment by guillaumebriday** [comment] 2021-04-09 09:35
Oups sorry didn't see this issue in the first place!

Could show me more code? Or create a reproduction repo?

thanks

**Comment by darylhai** [comment] 2021-04-10 00:31
Sure, I'm just following the GoRails tutorial and haven't hooked up any events yet.

information_apps_bulk_controller.js:
`import CheckboxSelectAll from "stimulus-checkbox-select-all"

export default class extends CheckboxSelectAll {
}`

_form.html.erb:
`<%= form_with model: @informationasset, data: { controller: 'information-apps-bulk' } do |f| %>
  <label>
    <input type="checkbox" data-checkbox-select-all-target="information-apps-bulk.checkboxAll" />
    <span>Select All / Deselect All</span>
  </label>

  <%= f.collection_check_boxes :app_ids, @apps_all, :id, :title do |b| %>
    <%= b.label do %>
      <%= b.check_box data: { target_checkbox_select_all: 'information-apps-bulk.checkbox' } %>
      <%= b.text %>
    <% end %>
  <% end %>

  <div class="mb-3">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>`

Full error is:
Uncaught TypeError: Class constructor _class cannot be invoked without 'new'
    at new _default (information_apps_bulk_controller.js?e1d1:2)
    at new extended (blessing.js?9f8c:77)
    at new Context (context.js?191d:7)
    at Module.fetchContextForScope (module.js?4a50:46)
    at Module.connectContextForScope (module.js?4a50:32)
    at Router.scopeConnected (router.js?29a8:92)
    at ScopeObserver.elementMatchedValue (scope_observer.js?6887:41)
    at ValueListObserver.tokenMatched (value_list_observer.js?dd8e:44)
    at TokenListObserver.tokenMatched (token_list_observer.js?f6b3:60)
    at eval (token_list_observer.js?f6b3:53)

**Comment by guillaumebriday** [comment] 2021-04-11 19:55
Hum are you using Stimulus 1.x or 2.x?

**Comment by guillaumebriday** [comment] 2021-04-11 21:52
Because I tried:

```js
class InformationAppsBulk extends Controller {
 // ...
}

export default class extends InformationAppsBulk {

}
```

And it works fine

**Comment by guillaumebriday** [comment] 2021-04-28 08:57
closing for now, feel free to reopen if needed

**Closed by guillaumebriday** 2021-04-28 08:57 UTC

**Comment by tsubik** [comment] 2021-05-05 20:00
I had exactly the same error when trying to upgrade to prerelease webpacker 6.0 to test webpack 5 integration. Turns out in the new babel config it was set `loose: true` for `babel-preset-env` and that line was causing it https://github.com/rails/webpacker/blob/a7190f5/package/babel/preset.js#L28. So if anyone has this error that must be something wrong with babel configuration.

**Comment by mabras** [comment] 2021-06-06 07:31
> when trying to upgrade to prerelease webpacker 6.0 to test webpack 5

I am just doing that. What should I do? I changed the value to `false` and remove it. I am still getting the error.

Thanks,
